# Apifox Helper 插件配置
# https://docs.apifox.com/5801721m0

# 使用 tag `folder` 设置接口所在目录
folder.name=#folder

# 忽略参数注解
param.ignore=groovy:return \
it.hasAnn("com.weutil.common.annotation.UserId") || \
it.hasAnn("com.weutil.common.annotation.ClientIp")

# 将 java.time.Instant 类型转换为 Long，Apifox 中以时间戳形式展示
json.rule.convert[java.time.Instant]=java.lang.Long

# 将 ErrorInfo 转换为 StandardResponse，Apifox 中以标准响应结构展示
json.rule.convert[com.weutil.common.model.response.ErrorInfo]=com.weutil.common.model.response.StandardResponse

# 使用 tag `example` 设置字段示例值
field.example=#example
